AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  myDateTimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myDateTimeFunction.handler
      Runtime: nodejs8.10
      AutoPublishAlias: live
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: '*'
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Hooks:
          PreTraffic:
            Ref: beforeAllowTraffic
          PostTraffic:
            Ref: afterAllowTraffic
      CodeUri: s3://buckettestvsti/99b5d8fb5de80fd3b2f2ea7847428101
  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:us-east-2:402182059433:deploymentgroup:${ServerlessDeploymentApplication}/*
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: myDateTimeFunction.Version
      Runtime: nodejs8.10
      FunctionName: CodeDeployHook_beforeAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: myDateTimeFunction.Version
      CodeUri: s3://buckettestvsti/99b5d8fb5de80fd3b2f2ea7847428101
  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:us-east-2:402182059433:deploymentgroup:${ServerlessDeploymentApplication}/*
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: myDateTimeFunction.Version
      Runtime: nodejs8.10
      FunctionName: CodeDeployHook_afterAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: myDateTimeFunction.Version
      CodeUri: s3://buckettestvsti/99b5d8fb5de80fd3b2f2ea7847428101
